---
title: "Clean and Combine Archive Data"
output: html_notebook
---

## Libraries

```{r}
library(googlesheets4)
library(tidyverse)
```

## Sheets Connection

```{r}
# gs4_auth(email = "") 
gs4_auth(cache = ".secrets", email = TRUE, use_oob = TRUE)
```

## Season 14

```{r warning=FALSE}
start_time = Sys.time()

sheet_id_14 = "1m45w0hQOkvUFvNpc5MwQcN4snGs0Lkrb6kJfOUJf6tw"

#Share Numbers tab
sn_14 = range_read(sheet_id_14
                ,sheet = 'share_numbers'
                ,col_types = 'icccicD-'
)

#Farmer Produce tab
fp_14 = range_read(sheet_id_14
                ,sheet = 'farm_produce'
                ,skip = 1
                ,col_types = 'icccnnnnncD'
)

#Weekly Share Lists tab
wsl_14 = range_read(sheet_id_14
                 ,sheet = 'weekly_share_lists'
                 ,col_types = 'iccicin--D'
)

#Weekly Par tab
wp_14 = range_read(sheet_id_14
                 ,sheet = 'weekly_par'
                 ,skip = 1
                 ,col_types = 'iccnccicD'
)

#Inventory Sales tab
is_14 = range_read(sheet_id_14
                ,sheet = 'inv_sales'
                ,col_types = 'iccccnnccD--'
)

#Master Item List tab
mil_14 = range_read(sheet_id_14
                 ,sheet = 'master_item_list'
                 ,col_types = 'cccccccnccnD'
)

#Share List tab
################
sl_14 = range_read(sheet_id_14
                ,sheet = 'share_list'
                ,col_types = 'ccniD'
)

#Default Par tab
################

#Share Rotation tab
sr_14 = range_read(sheet_id_14
                ,sheet = 'share_rotation'
                ,col_types = '----Dicic----------'
)

#Farmer List tab
################
fl_14 = range_read(sheet_id_14
                ,sheet = 'farmer_list'
                ,col_types = 'ccccccD'
)

#Produce Per List tab
################

#Storage Location tab
################

rm(sheet_id_14)

```

## Season 15

```{r}
sheet_id_15 = "125T2Gz-LJ9hyVivRasRD-Uzm-avJIbJfKN2ACqNrHM0"

#Share Numbers tab
sn_15 = range_read(sheet_id_15
                ,sheet = 'share_numbers'
                ,col_types = 'icccicD-'
)

#Farmer Produce tab
fp_15 = range_read(sheet_id_15
                ,sheet = 'farm_produce'
                ,skip = 1
                ,col_types = 'icccnnnnncD'
)

#Weekly Share Lists tab
wsl_15 = range_read(sheet_id_15
                 ,sheet = 'weekly_share_lists'
                 ,col_types = 'iccicin--D'
)

#Weekly Par tab
wp_15 = range_read(sheet_id_15
                 ,sheet = 'weekly_par'
                 ,skip = 1
                 ,col_types = 'iccnccicD'
)

#Inventory Sales tab
is_15 = range_read(sheet_id_15
                ,sheet = 'inv_sales'
                ,col_types = 'iccccnnccD--'
)

#Master Item List tab
mil_15 = range_read(sheet_id_15
                 ,sheet = 'master_item_list'
                 ,col_types = 'cccccccnccnD'
)

#Share List tab
################
sl_15 = range_read(sheet_id_15
                ,sheet = 'share_list'
                ,col_types = 'ccniD'
)

#Default Par tab
################

#Share Rotation tab
sr_15 = range_read(sheet_id_15
                ,sheet = 'share_rotation'
                ,col_types = '----Dicic----------'
)

#Farmer List tab
################
fl_15 = range_read(sheet_id_15
                ,sheet = 'farmer_list'
                ,col_types = 'ccccccD'
)

#Produce Per List tab
################

#Storage Location tab
################

rm(sheet_id_15)
```

## Season 15

```{r}
sheet_id_16 = "1Jo2p-q4CBucAhYu3SWaCxjtLLAM26F8-RGcczwvOhqk"

#Share Numbers tab
sn_16 = range_read(sheet_id_16
                ,sheet = 'share_numbers'
                ,col_types = 'icccicD-'
)

#Farmer Produce tab
fp_16 = range_read(sheet_id_16
                ,sheet = 'farm_produce'
                ,skip = 1
                ,col_types = 'icccnnnnncD'
)

#Weekly Share Lists tab
wsl_16 = range_read(sheet_id_16
                 ,sheet = 'weekly_share_lists'
                 ,col_types = 'iccicin--D'
)

#Weekly Par tab
wp_16 = range_read(sheet_id_16
                 ,sheet = 'weekly_par'
                 ,skip = 1
                 ,col_types = 'iccnccicD'
)

#Inventory Sales tab
is_16 = range_read(sheet_id_16
                ,sheet = 'inv_sales'
                ,col_types = 'iccccnnccD--'
)

#Master Item List tab
mil_16 = range_read(sheet_id_16
                 ,sheet = 'master_item_list'
                 ,col_types = 'cccccccnccnD'
)

#Share List tab
################
sl_16 = range_read(sheet_id_16
                ,sheet = 'share_list'
                ,col_types = 'ccniD'
)

#Default Par tab
################

#Share Rotation tab
sr_16 = range_read(sheet_id_16
                ,sheet = 'share_rotation'
                ,col_types = '----Dicic----------'
)

#Farmer List tab
################
fl_16 = range_read(sheet_id_16
                ,sheet = 'farmer_list'
                ,col_types = 'ccccccD'
)

#Produce Per List tab
################

#Storage Location tab
################

rm(sheet_id_16)
```

## Combine Data

```{r}
#Share Numbers tab
c_sn = sn_14 |> 
  mutate(season = 's14') |> 
  bind_rows(sn_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(sn_16 |> 
              mutate(season = 's16')
            ) 

#Farmer Produce tab
c_fp = fp_14 |> 
  mutate(season = 's14') |> 
  bind_rows(fp_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(fp_16 |> 
              mutate(season = 's16')
            )

#Weekly Share Lists tab
c_wsl = wsl_14 |> 
  mutate(season = 's14') |> 
  bind_rows(wsl_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(wsl_16 |> 
              mutate(season = 's16')
            )

#Weekly Par tab
c_wp = wp_14 |> 
  mutate(season = 's14') |> 
  bind_rows(wp_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(wp_16 |> 
              mutate(season = 's16')
            )

#Inventory Sales tab
c_is = is_14 |> 
  mutate(season = 's14') |> 
  bind_rows(is_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(is_16 |> 
              mutate(season = 's16')
            )

#Master Item List tab
c_mil = mil_14 |> 
  mutate(season = 's14') |> 
  bind_rows(mil_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(mil_16 |> 
              mutate(season = 's16')
            )

#Share List tab
################
c_sl = sl_14 |> 
  mutate(season = 's14') |> 
  bind_rows(sl_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(sl_16 |> 
              mutate(season = 's16')
            )

#Default Par tab
################

#Share Rotation tab
c_sr = sr_14 |> 
  mutate(season = 's14') |> 
  bind_rows(sr_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(sr_16 |> 
              mutate(season = 's16')
            )

#Farmer List tab
################
c_fl = fl_14 |> 
  mutate(season = 's14') |> 
  bind_rows(fl_15 |> 
              mutate(season = 's15')
            ) |> 
  bind_rows(fl_16 |> 
              mutate(season = 's16')
            )

#Produce Per List tab
################
```

## Clean Data

```{r}
#Share Numbers tab
cc_sn = c_sn |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) |> 
  filter(!is.na(week))

#Farmer Produce tab
cc_fp_v1 = c_fp |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) |> 
  mutate(av_min = ifelse(is.na(av_min), 0, av_min)
         ,av_max = ifelse(is.na(av_max), 0, av_max)
         ,order = ifelse(is.na(order), 0, order)
         ,store = ifelse(is.na(store), 0, store)
         ,store_note = ifelse(is.na(store_note), '', store_note)) |> 
  mutate(clean = ifelse(av_min > 0 | av_max > 0 | order > 0 | store > 0 | store_note != '', 1, 0)) 

stopifnot(cc_fp_v1 |> filter(is.na(clean)) |> summarise(n = n()) |> pull() == 0)

cc_fp = cc_fp_v1 |> 
  filter(!is.na(item)) |> 
  filter(clean == 1) |> 
  select(-clean) |> 
  mutate(store_note = ifelse(store_note == '', NA, store_note))

#Weekly Share Lists tab
cc_wsl = c_wsl |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) |> 
  filter(!is.na(item) & !is.na(week) & !is.na(item_nu))

#Weekly Par tab
cc_wp = c_wp |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) |> 
  rename(week = wk_start) |> 
  filter(!is.na(item) & !is.na(week) & !is.na(producer)) 

#Inventory Sales tab
cc_is = c_is |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) |> 
  rename(invent_manual = invent._manual) |> 
  mutate(invent_from_farmigo = ifelse(is.na(invent_from_farmigo), 0, invent_from_farmigo)
         ,invent_manual = ifelse(is.na(invent_manual), 0, invent_manual)
         ,clean = ifelse(invent_from_farmigo > 0 | invent_manual > 0 | !is.na(inventory_note) | !is.na(sold), 1, 0)
         )

stopifnot(cc_is |> filter(is.na(clean)) |> summarise(n = n()) |> pull() == 0)

# cc_is = cc_is_v1 |> 
#   filter(clean == 1) |> 
#   select(-clean)

#Master Item List tab
cc_mil = c_mil |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) |> 
  filter(!is.na(category) | !is.na(type) | !is.na(preferred_per_value))

#Share List tab
################
cc_sl = c_sl |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) 

#Default Par tab
################

#Share Rotation tab
cc_sr = c_sr |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) |> 
  rename(week = 'week_#') 

#Farmer List tab
################
cc_fl = c_fl |> 
  rename_all(tolower) |> 
  select_all(list(~gsub(" ", "_", .))) 

#Produce Per List tab
################
```

## Add New Columns

```{r}
#Share Numbers tab
ccc_sn = cc_sn |> 
  left_join(cc_sr |> 
              select(season, week, date) |> 
              distinct()
            , by = c('season','week')) |> 
  mutate(season_week = paste0(str_replace(season,'s',''),'.',
                              ifelse(week < 0, '-01',
                                     ifelse(str_length(week)==1,paste0('0',week),week))
                              )
         )

#Farmer Produce tab
ccc_fp = cc_fp |> 
  left_join(cc_sr |> 
              select(season, week, date) |> 
              distinct()
            , by = c('season','week')) |> 
  mutate(season_week = paste0(str_replace(season,'s',''),'.',
                              ifelse(week < 0, '-01',
                                     ifelse(str_length(week)==1,paste0('0',week),week))
                              )
         )

#Weekly Share Lists tab
ccc_wsl = cc_wsl |> 
  left_join(cc_sr |> 
              select(season, week, date) |> 
              distinct()
            , by = c('season','week')) |> 
  mutate(season_week = paste0(str_replace(season,'s',''),'.',
                              ifelse(week < 0, '-01',
                                     ifelse(str_length(week)==1,paste0('0',week),week))
                              )
         )

#Weekly Par tab
################
ccc_wp = cc_wp  |> 
  left_join(cc_sr |> 
              select(season, week, date) |> 
              distinct()
            , by = c('season','week')) |> 
  mutate(season_week = paste0(str_replace(season,'s',''),'.',
                              ifelse(week < 0, '-01',
                                     ifelse(str_length(week)==1,paste0('0',week),week))
                              )
         )

#Inventory Sales tab
ccc_is = cc_is  |> 
  left_join(cc_sr |> 
              select(season, week, date) |> 
              distinct()
            , by = c('season','week')) |> 
  mutate(season_week = paste0(str_replace(season,'s',''),'.',
                              ifelse(week < 0, '-01',
                                     ifelse(str_length(week)==1,paste0('0',week),week))
                              )
         )

#Master Item List tab
ccc_mil = cc_mil

#Share List tab
################
ccc_sl = cc_sl

#Default Par tab
################

#Share Rotation tab
ccc_sr = cc_sr |> 
  mutate(season_week = paste0(str_replace(season,'s',''),'.',
                              ifelse(week < 0, '-01',
                                     ifelse(str_length(week)==1,paste0('0',week),week))
                              )
         )

#Farmer List tab
################
ccc_fl = cc_fl

#Produce Per List tab
################
```

## Create new data sets

```{r}
#Clean version
ccc_is_cl = ccc_is |> 
  filter(clean == 1) |> 
  select(-clean)

#Sales Only
ccc_so = ccc_is |> 
  filter(clean == 1) |> 
  select(-clean) |> 
  filter(!is.na(sold)) |> 
  select(week, producer, item, sold, archive_date, season, date, season_week)

```

## Upload Data to Google Sheets

### Upload Function

Had to create this since rate limits are now (Dec 16,2022) affecting uploads. 

```{r eval=FALSE, include=FALSE}

google_sheets_upload = function(data, sheet, tab, n_rows, sleep_sec) {
  upload_rows = n_rows
  max_loops = ceiling(nrow(data) / upload_rows)
  st = 0
  en = upload_rows
  
  start_time = Sys.time()
  
  for (i in 1:max_loops) {
    # print(i)
    if (i == 1) {
      sheet_write(data |> slice((st+1):en), sheet, sheet = tab)
      st = st+upload_rows
      en = en+upload_rows
      Sys.sleep(sleep_sec)
      # print(st)
      # print(en)
    } else if (i == max_loops) {
      sheet_append(ss = sheet, data |> slice((st+1):en), sheet = tab)
    } else {
      sheet_append(ss = sheet, data |> slice((st+1):en), sheet = tab)
      st = st+upload_rows
      en = en+upload_rows
      Sys.sleep(sleep_sec)
      # print(st)
      # print(en)
    }
  }
  end_time = Sys.time()
  
  start_time
  end_time
}


```

### Practice function

```{r eval=FALSE, include=FALSE}
upload_rows = 100
max_loops = ceiling(nrow(ccc_sn) / upload_rows)
st = 1
en = upload_rows

start_time = Sys.time()

for (i in 1:max_loops) {
  # print(i)
  if (i == 1) {
    sheet_write(ccc_sn |> slice((st+1):en), sheet_id_ccc, sheet = "share_numbers")
    st = st+upload_rows
    en = en+upload_rows
    # print(st)
    # print(en)
  } else if (i == max_loops) {
    sheet_append(ss = sheet_id_ccc, ccc_sn |> slice((st+1):en), sheet = "share_numbers")
  } else {
    sheet_append(ss = sheet_id_ccc, ccc_sn |> slice((st+1):en), sheet = "share_numbers")
    st = st+upload_rows
    en = en+upload_rows
    # print(st)
    # print(en)
  }
}
end_time = Sys.time()

start_time
end_time
```

### Run Functions

```{r}
sheet_id_ccc = "1xs8TAMrSsJuL_gou4y0DBH3IkaTH0eBn_pdboCGWFTI"

#Share Numbers tab
sheet_write(ccc_sn, sheet_id_ccc, sheet = "share_numbers")
# google_sheets_upload(ccc_sn, sheet_id_ccc, "share_numbers", 50, 2)

#Farmer Produce tab
sheet_write(ccc_fp, sheet_id_ccc, sheet = "farm_produce")
# google_sheets_upload(ccc_fp, sheet_id_ccc, "farm_produce", 200)

#Weekly Share Lists tab
sheet_write(ccc_wsl, sheet_id_ccc, sheet = "weekly_share_lists")
# google_sheets_upload(ccc_wsl, sheet_id_ccc, "weekly_share_lists", 200)

#Weekly Par tab
sheet_write(ccc_wp, sheet_id_ccc, sheet = "weekly_par")

#Inventory Sales tab
sheet_write(ccc_is |> 
              select(-clean)
  , sheet_id_ccc, sheet = "inv_sales")
# google_sheets_upload(ccc_is, sheet_id_ccc, "inv_sales", 200)

#Master Item List tab
sheet_write(ccc_mil, sheet_id_ccc, sheet = "master_item_list")
# google_sheets_upload(ccc_mil, sheet_id_ccc, "master_item_list", 200)

#Share List tab
################
sheet_write(ccc_sl, sheet_id_ccc, sheet = "share_list")
# google_sheets_upload(ccc_sl, sheet_id_ccc, "share_list", 200)

#Default Par tab
################

#Share Rotation tab
sheet_write(ccc_sr, sheet_id_ccc, sheet = "share_rotation")
# google_sheets_upload(ccc_sr, sheet_id_ccc, "share_rotation", 200)

#Farmer List tab
################
sheet_write(ccc_fl, sheet_id_ccc, sheet = "farmer_list")
# google_sheets_upload(ccc_fl, sheet_id_ccc, "farmer_list", 200)

#Produce Per List tab
################

############# New Tables ############# 
#Clean Inv Sales tab
sheet_write(ccc_is_cl, sheet_id_ccc, sheet = "inv_sales_clean")

#Sales Only tab
sheet_write(ccc_so, sheet_id_ccc, sheet = "sales_only")
# google_sheets_upload(ccc_so, sheet_id_ccc, "sales_only", 200)

end_time = Sys.time()

start_time
end_time
```

## Data Checks

```{r}

```

